// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeleniumRecorderApi.Data;

#nullable disable

namespace SeleniumRecorderApi.Migrations;

[DbContext(typeof(AwaitDbContext))]
[Migration("20230611125544_initWebElement")]
partial class initWebElement
{
    /// <inheritdoc />
    protected void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("SeleniumRecorder.Models.WebElementEventResult", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("ElementCSSPath")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ElementClassName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ElementId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ElementTag")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ElementWindowLocation")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ElementXPath")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("EventType")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("WebElements");
            });
#pragma warning restore 612, 618
    }
}
